---
notifications:
  email:
    on_success: never
    on_failure: change

cache: pip

sudo: true

language: python

python:
  - '2.7'
  - '3.6'

install:
  - sudo apt-get install -y libgit2{,-dev}
  - pip install coveralls
  - python setup.py install

script:
  - python setup.py test

after_script:
  - coveralls
