---
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-7s - %(message)s'
    datefmt: '%H:%M:%S'
handlers:
  hidden:
    class: logging.handlers.MemoryHandler
    capacity: 1024
  memory:
    class: logging.handlers.MemoryHandler
    capacity: 1024 * 1024
    target: console
    level: SPAM
    formatter: simple
  console:
    class: logging.StreamHandler
    level: SPAM
    stream: ext://sys.stdout
    formatter: simple
loggers:
  gitflow_wotw:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: WARNING
  handlers: [hidden]
